创建ndarry及数据类型

In [1]:
import numpy as np

In [2]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [3]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr2.ndim

2

In [5]:
arr2.shape

(2, 4)

In [6]:
print(arr1.dtype, arr2.dtype)

(dtype('float64'), dtype('int64'))


In [7]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [8]:
np.zeros((3, 4, 5))

array([[[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]])

In [9]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [10]:
np.empty((2,3,2))

array([[[  6.92372310e-310,   9.71267448e-317],
        [  6.92371500e-310,   1.27319747e-313],
        [  1.27319747e-313,   1.27319747e-313]],

       [[  1.27319747e-313,   1.27319747e-313],
        [  6.92371500e-310,   6.92364787e-310],
        [  2.61352681e-313,   6.42285340e-323]]])

In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [13]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [14]:
np.array([1,2,3], np.float64)

array([ 1.,  2.,  3.])

In [15]:
np.array([1,2,3], np.int32)

array([1, 2, 3], dtype=int32)

In [16]:
np.array([1.2, 3.4, 5.6]).astype(np.int32)

array([1, 3, 5], dtype=int32)

In [17]:
np.array([1.2, 3.4, 5.6]).astype(arr2.dtype)

array([1, 3, 5])

与标量之间的计算

In [18]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [19]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [20]:
arr * arr * arr

array([[   1.,    8.,   27.],
       [  64.,  125.,  216.]])

In [21]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [22]:
arr + arr

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [23]:
arr / arr

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [24]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [25]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

基本的索引和切片

In [26]:
arr = np.arange(10)

In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr[5]

5

In [29]:
arr[5:8]

array([5, 6, 7])

In [30]:
arr[5:8] = 12

In [31]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [32]:
arr_slice = arr[5:8]
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [33]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [34]:
arr_copy = arr[5:8].copy()
arr_copy[1] = 12345
print(arr)
print(arr_copy)

[ 0  1  2  3  4 64 64 64  8  9]
[   64 12345    64]


In [35]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr2d[2]

array([7, 8, 9])

In [37]:
arr2d[0][2]

3

In [38]:
arr2d[0,2]

3

In [39]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [40]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
old_values = arr3d[0].copy()
print(old_values)
arr3d[0] = 42
print(arr3d)
arr3d[0] = old_values
print(arr3d)

[[1 2 3]
 [4 5 6]]
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [42]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [43]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [46]:
(arr2d[1, :2], arr2d[2, :1], arr2d[:, :1])

(array([4, 5]), array([7]), array([[1],
        [4],
        [7]]))

布尔型索引

In [47]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='|S4')

In [48]:
data = np.random.randn(7, 4)
data

array([[-0.80622482, -0.5381852 , -0.00821656,  0.81322033],
       [ 1.18831371,  1.12736252, -0.69541713, -0.39757097],
       [ 0.76354004,  0.4943048 ,  0.08167556,  0.02576064],
       [ 0.67268763,  0.15669691,  0.36151569,  0.61408111],
       [ 0.51561893, -0.53826755,  0.17301539, -2.33304963],
       [-0.17428007, -1.19828255,  1.37064073, -0.83074932],
       [ 0.59886815,  0.54646716,  2.49493809, -0.10580156]])

In [49]:
names == "Bob"

array([ True, False, False,  True, False, False, False], dtype=bool)

In [50]:
data[names == "Bob"]

array([[-0.80622482, -0.5381852 , -0.00821656,  0.81322033],
       [ 0.67268763,  0.15669691,  0.36151569,  0.61408111]])

In [51]:
data[names == "Bob", 2:]

array([[-0.00821656,  0.81322033],
       [ 0.36151569,  0.61408111]])

In [52]:
names != "Bob"
data[~(names == "Bob")]

array([[ 1.18831371,  1.12736252, -0.69541713, -0.39757097],
       [ 0.76354004,  0.4943048 ,  0.08167556,  0.02576064],
       [ 0.51561893, -0.53826755,  0.17301539, -2.33304963],
       [-0.17428007, -1.19828255,  1.37064073, -0.83074932],
       [ 0.59886815,  0.54646716,  2.49493809, -0.10580156]])

In [53]:
mask = (names == "Bob") | (names == "Will")
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [54]:
mask2 = (names == "Bob") & (names == "Will")
mask2

array([False, False, False, False, False, False, False], dtype=bool)

In [55]:
data[data < 0] = 0
data

array([[ 0.        ,  0.        ,  0.        ,  0.81322033],
       [ 1.18831371,  1.12736252,  0.        ,  0.        ],
       [ 0.76354004,  0.4943048 ,  0.08167556,  0.02576064],
       [ 0.67268763,  0.15669691,  0.36151569,  0.61408111],
       [ 0.51561893,  0.        ,  0.17301539,  0.        ],
       [ 0.        ,  0.        ,  1.37064073,  0.        ],
       [ 0.59886815,  0.54646716,  2.49493809,  0.        ]])

花式索引

In [4]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [6]:
arr[[4, 3, 0, 6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [8]:
arr[[-3, -5 , -7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [15]:
arr = np.arange(32)
arr
arr = np.reshape(np.arrange(32), (8, 4))
arr

AttributeError: 'module' object has no attribute 'arrange'