创建ndarry及数据类型

In [1]:
import numpy as np

In [2]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [3]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr2.ndim

2

In [5]:
arr2.shape

(2, 4)

In [6]:
print(arr1.dtype, arr2.dtype)

(dtype('float64'), dtype('int64'))


In [7]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [8]:
np.zeros((3, 4, 5))

array([[[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]])

In [9]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [10]:
np.empty((2,3,2))

array([[[  6.93198338e-310,   2.74377578e-316],
        [  4.72327548e-317,   6.93197693e-310],
        [  0.00000000e+000,   0.00000000e+000]],

       [[  0.00000000e+000,   4.79243676e-322],
        [  6.93198338e-310,   6.93198338e-310],
        [  0.00000000e+000,   0.00000000e+000]]])

In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [13]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [14]:
np.array([1,2,3], np.float64)

array([ 1.,  2.,  3.])

In [15]:
np.array([1,2,3], np.int32)

array([1, 2, 3], dtype=int32)

In [16]:
np.array([1.2, 3.4, 5.6]).astype(np.int32)

array([1, 3, 5], dtype=int32)

In [17]:
np.array([1.2, 3.4, 5.6]).astype(arr2.dtype)

array([1, 3, 5])

与标量之间的计算

In [18]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [19]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [20]:
arr * arr * arr

array([[   1.,    8.,   27.],
       [  64.,  125.,  216.]])

In [21]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [22]:
arr + arr

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [23]:
arr / arr

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [24]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [25]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

基本的索引和切片

In [26]:
arr = np.arange(10)

In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr[5]

5

In [29]:
arr[5:8]

array([5, 6, 7])

In [30]:
arr[5:8] = 12

In [31]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [32]:
arr_slice = arr[5:8]
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [33]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [34]:
arr_copy = arr[5:8].copy()
arr_copy[1] = 12345
print(arr)
print(arr_copy)

[ 0  1  2  3  4 64 64 64  8  9]
[   64 12345    64]


In [35]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr2d[2]

array([7, 8, 9])

In [37]:
arr2d[0][2]

3

In [38]:
arr2d[0,2]

3

In [39]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [40]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
old_values = arr3d[0].copy()
print(old_values)
arr3d[0] = 42
print(arr3d)
arr3d[0] = old_values
print(arr3d)

[[1 2 3]
 [4 5 6]]
[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [42]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [43]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [46]:
(arr2d[1, :2], arr2d[2, :1], arr2d[:, :1])

(array([4, 5]), array([7]), array([[1],
        [4],
        [7]]))

布尔型索引

In [47]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'],
      dtype='|S4')

In [48]:
data = np.random.randn(7, 4)
data

array([[ 1.91395546, -0.15653853,  0.10923029, -0.01233654],
       [-0.61993737,  1.30890535,  0.89028787,  0.23544746],
       [-0.64025998, -1.23688915, -0.08638412, -0.31120667],
       [-0.69478551,  0.19423163, -1.2790008 , -0.37632862],
       [-0.07356107, -0.34330055,  0.54682077, -0.28673346],
       [ 1.31234092,  0.74718786,  0.68805751,  1.28848535],
       [-0.96878518,  1.52771638,  0.55244569, -0.18495821]])

In [49]:
names == "Bob"

array([ True, False, False,  True, False, False, False], dtype=bool)

In [50]:
data[names == "Bob"]

array([[ 1.91395546, -0.15653853,  0.10923029, -0.01233654],
       [-0.69478551,  0.19423163, -1.2790008 , -0.37632862]])

In [51]:
data[names == "Bob", 2:]

array([[ 0.10923029, -0.01233654],
       [-1.2790008 , -0.37632862]])

In [52]:
names != "Bob"
data[~(names == "Bob")]

array([[-0.61993737,  1.30890535,  0.89028787,  0.23544746],
       [-0.64025998, -1.23688915, -0.08638412, -0.31120667],
       [-0.07356107, -0.34330055,  0.54682077, -0.28673346],
       [ 1.31234092,  0.74718786,  0.68805751,  1.28848535],
       [-0.96878518,  1.52771638,  0.55244569, -0.18495821]])

In [53]:
mask = (names == "Bob") | (names == "Will")
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [54]:
mask2 = (names == "Bob") & (names == "Will")
mask2

array([False, False, False, False, False, False, False], dtype=bool)

In [55]:
data[data < 0] = 0
data

array([[ 1.91395546,  0.        ,  0.10923029,  0.        ],
       [ 0.        ,  1.30890535,  0.89028787,  0.23544746],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.19423163,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.54682077,  0.        ],
       [ 1.31234092,  0.74718786,  0.68805751,  1.28848535],
       [ 0.        ,  1.52771638,  0.55244569,  0.        ]])

花式索引

In [56]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [57]:
arr[[4, 3, 0, 6]]

array([[ 4.,  4.,  4.,  4.],
       [ 3.,  3.,  3.,  3.],
       [ 0.,  0.,  0.,  0.],
       [ 6.,  6.,  6.,  6.]])

In [58]:
arr[[-3, -5 , -7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [63]:
arr = np.arange(32)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [64]:
arr = np.reshape(np.arange(32), (8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [66]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

数组转置和轴兑换

In [69]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [71]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [73]:
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [75]:
np.dot(arr, arr.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [81]:
arr = np.random.randn(16).reshape((4,4)).reshape((2,2,4))
arr

array([[[-0.77750574,  0.93327951,  0.03717773,  0.01689887],
        [ 0.60085953, -0.79671862, -1.00441328,  1.06482705]],

       [[-1.62678057, -0.15282441, -0.73422518,  0.38970865],
        [ 0.35166918,  0.79236618, -1.02870955, -0.68674878]]])

In [85]:
arr = np.arange(16).reshape((4,4)).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [86]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [87]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

快速的元素级数组函数

In [89]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [93]:
x = np.random.randn(8)
y = np.random.randn(8)
print(x)
print(y)
print(np.maximum(x, y))

[-1.06343935  0.5120086  -0.63832927  0.88122047  2.04968077  0.95007839
  0.88755924 -1.11407736]
[-0.69056967  0.35138852 -0.8747935  -0.3044858   1.07353821  1.37251663
 -0.07009361 -0.87437988]
[-0.69056967  0.5120086  -0.63832927  0.88122047  2.04968077  1.37251663
  0.88755924 -0.87437988]
