创建ndarry及数据类型

In [1]:
import numpy as np

In [2]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [3]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr2.ndim

2

In [5]:
arr2.shape

(2, 4)

In [6]:
print(arr1.dtype, arr2.dtype)

(dtype('float64'), dtype('int64'))


In [7]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [8]:
np.zeros((3, 4, 5))

array([[[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]])

In [9]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [10]:
np.empty((2,3,2))

array([[[  6.94920969e-310,   2.04474878e-316],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]],

       [[  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000],
        [  0.00000000e+000,   0.00000000e+000]]])

In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [13]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [14]:
np.array([1,2,3], np.float64)

array([ 1.,  2.,  3.])

In [15]:
np.array([1,2,3], np.int32)

array([1, 2, 3], dtype=int32)

In [16]:
np.array([1.2, 3.4, 5.6]).astype(np.int32)

array([1, 3, 5], dtype=int32)

In [17]:
np.array([1.2, 3.4, 5.6]).astype(arr2.dtype)

array([1, 3, 5])

与标量之间的计算

In [18]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [19]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])

In [20]:
arr * arr * arr

array([[   1.,    8.,   27.],
       [  64.,  125.,  216.]])

In [21]:
arr - arr

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [22]:
arr + arr

array([[  2.,   4.,   6.],
       [  8.,  10.,  12.]])

In [23]:
arr / arr

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [24]:
1 / arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [25]:
arr ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

基本的索引和切片

In [26]:
arr = np.arange(10)

In [27]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr[5]

5

In [29]:
arr[5:8]

array([5, 6, 7])

In [30]:
arr[5:8] = 12

In [31]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [32]:
arr_slice = arr[5:8]
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [33]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])