创建ndarry及数据类型

In [1]:
import numpy as np

In [2]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([ 6. ,  7.5,  8. ,  0. ,  1. ])

In [3]:
data2 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
arr2.ndim

2

In [5]:
arr2.shape

(2, 4)

In [6]:
print(arr1.dtype, arr2.dtype)

(dtype('float64'), dtype('int64'))


In [7]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [8]:
np.zeros((3, 4, 5))

array([[[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]])

In [20]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [9]:
np.empty((2,3,2))

array([[[  6.91522640e-310,   1.76263887e-316],
        [  6.91520835e-310,   6.91520835e-310],
        [  6.91520835e-310,   6.91520835e-310]],

       [[  6.91520835e-310,   6.91520835e-310],
        [  6.91520835e-310,   6.91520835e-310],
        [  6.91520835e-310,   3.21142670e-322]]])

In [10]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [18]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [21]:
np.array([1,2,3], np.float64)

array([ 1.,  2.,  3.])

In [22]:
np.array([1,2,3], np.int32)

array([1, 2, 3], dtype=int32)

In [23]:
np.array([1.2, 3.4, 5.6]).astype(np.int32)

array([1, 3, 5], dtype=int32)

In [25]:
np.array([1.2, 3.4, 5.6]).astype(arr2.dtype)

array([1, 3, 5])

与标量之间的计算

In [28]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [27]:
arr * arr

array([[  1.,   4.,   9.],
       [ 16.,  25.,  36.]])